$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  bwa_mem:
    type: object
    description: parameters for bwa mem
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      sorting:
        type: string
        description: program hangling the bam sorting (default samtools)
      sort_order:
        type: string
        description: how the bam file should be sorted (default coordinate)
      sort_extra:
        type: string
        description: parameters that should be forwarded to sorting (ie, number of threads)
      amb:
        mt:
          type: string
          description: mt fasta reference amb file
        mt_shifted:
          type: string
          description: mt_shifted fasta reference amb file
      ann:
        mt:
          type: string
          description: mt fasta reference ann file
        mt_shifted:
          type: string
          description: mt_shifted fasta reference ann file
      bwt:
        mt:
          type: string
          description: mt fasta reference bwt file
        mt_shifted:
          type: string
          description: mt_shifted fasta reference bwt file
      pac:
        mt:
          type: string
          description: mt fasta reference pac file
        mt_shifted:
          type: string
          description: mt_shifted fasta reference pac file
      sa:
        mt:
          type: string
          description: mt fasta reference sa file
        mt_shifted:
          type: string
          description: mt_shifted fasta reference sa file
    required:
      - amb
      - ann
      - bwt
      - pac
      - sa

  gatk_collect_wgs_metrics:
    type: object
    description: collect wgs metrics settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      coverage_cap:
        type: number
        description: set coverage cap to this number
      read_length:
        type: number
        description: average read length in the file
      extra:
        type: string
        description: parameters that should be forwarded
  
  gatk_lift_over_vcf:
    type: object
    description: lift over VCF settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mark_duplicates:
    type: object
    description: mark duplicates settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_merge_bam_alignment:
    type: object
    description: merge BAM alignment settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_merge_vcfs:
    type: object
    description: merge VCF settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2:
    type: object
    description: mutect2 settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      interval:
        type: string
        description: interval list files
          mt: 
            type: string
            description: mitochondrial reference interval list file
          mt_shifted: 
            type: string
            description: shifted mitochondrial reference interval list file
      max_reads_per_alignment_start: 
        type: number
        description: Maximum number of reads to retain per alignment start position.

  reference:
    type: object
    description: reference used 
    properties:
      fasta:
        type: string
        description: fasta reference file
      fai:
        type: string
        description: fasta reference fai file
        
required:
  - samples
  - units
  - resources
  - default_container

    