$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  bwa_mem:
    type: object
    description: parameters for bwa mem
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      sorting:
        type: string
        description: program hangling the bam sorting (default samtools)
      sort_order:
        type: string
        description: how the bam file should be sorted (default coordinate)
      sort_extra:
        type: string
        description: parameters that should be forwarded to sorting (ie, number of threads)
      amb:
        type: object
        description: amb files
        properties:
          mt:
            type: string
            description: mt fasta reference amb file
          mt_shifted:
            type: string
            description: mt_shifted fasta reference amb file
      ann:
        type: object
        description: ann files
        properties:
          mt:
            type: string
            description: mt fasta reference ann file
          mt_shifted:
            type: string
            description: mt_shifted fasta reference ann file
      bwt:
        type: object
        description: bwt files
        properties:
          mt:
            type: string
            description: mt fasta reference bwt file
          mt_shifted:
            type: string
            description: mt_shifted fasta reference bwt file
      pac:
        type: object
        description: pac files
        properties:
          mt:
            type: string
            description: mt fasta reference pac file
          mt_shifted:
            type: string
            description: mt_shifted fasta reference pac file
      sa:
        type: object
        description: sa files
        properties:
          mt:
            type: string
            description: mt fasta reference sa file
          mt_shifted:
            type: string
            description: mt_shifted fasta reference sa file
    required:
      - amb
      - ann
      - bwt
      - pac
      - sa

  gatk_collect_wgs_metrics:
    type: object
    description: collect wgs metrics settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      coverage_cap:
        type: number
        description: set coverage cap to this number
      read_length:
        type: number
        description: average read length in the file
      extra:
        type: string
        description: parameters that should be forwarded
  
  gatk_lift_over_vcf:
    type: object
    description: lift over VCF settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mark_duplicates:
    type: object
    description: mark duplicates settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_merge_bam_alignment:
    type: object
    description: merge BAM alignment settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_merge_vcfs:
    type: object
    description: merge VCF settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2:
    type: object
    description: mutect2 settings
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      interval:
        type: object
        description: interval list files
        properties:
          mt: 
            type: string
            description: mitochondrial reference interval list file
          mt_shifted: 
            type: string
            description: shifted mitochondrial reference interval list file
      max_reads_per_alignment_start: 
        type: number
        description: Maximum number of reads to retain per alignment start position.

  gatk_print_reads:
    type: object
    description: print reads setting
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      interval: 
        type: string
        description: interval for print reads

  gatk_revert_sam:
    type: object
    description: revert sam setting
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_sam_to_fastq:
    type: object
    description: sam to fastq setting
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_sort_sam:
    type: object
    description: sort sam settings
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_variant_filtration:
    type: object
    description: variant filtration settings
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  haplocheck:
    type: object
    description: haplocheck settings
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  mt_reference:
    type: object
    description: mitochchondrial reference used 
    properties:
      mt:
        type: string
        description: fasta mitochondrial reference fasta file
      mt_shifted:
        type: string
        description: fasta mitochondrial shifter reference fasta file
      blacklist:
        type: string
        description: blacklisted mitochondrial sites bed file


required:
  - samples
  - units
  - resources
  - default_container

    